ds-prep-python-functions- Tiffany Lin
tiffanylin706/ds-py-0422-code-solutions pull request #3
Opened 2022-04-25 22:15 UTC by tiffanylin706

<img width="1358" alt="截圖 2022-04-25 下午3 08 09" src="https://user-images.githubusercontent.com/103457249/165183815-a7f99fdd-418b-40f3-b4b0-5d16d68209be.png">

2022-04-25 23:40 UTC, TimelikeClosure requested changes

2022-04-25 23:40 UTC, TimelikeClosure commented on ds-prep-python-functions/main.py
> +print ("square_difference:", ((abs(14-11))**2))
Please make sure your `squared_difference` function is properly calculating the square of the difference, so you're not forced to do the math outside the function.

2022-04-25 23:40 UTC, TimelikeClosure commented on ds-prep-python-functions/main.py
> +print ("get_circumference:", get_circumference (9.2))
Please call these with _keyword_ arguments only:

---

![image](https://user-images.githubusercontent.com/16143771/165191653-81e83394-8059-416a-997f-0093548c26a1.png)

2022-04-26 02:21 UTC, TimelikeClosure requested changes

2022-04-26 02:21 UTC, TimelikeClosure commented on ds-prep-python-functions/main.py
> +print ("absolue difference:", (abs (13-40)))
Please call the `absolute_difference` function to get these values. Make sure your `absolute_difference` function definition is using `abs` correctly: https://www.w3schools.com/python/ref_func_abs.asp

2022-04-26 02:21 UTC, TimelikeClosure commented on ds-prep-python-functions/main.py
> +print ("square_difference:", ((abs(14,11))**2))
Like above, please make sure you're calling the `squared_difference` function to get the value, not calculating it manually outside the function definition.

2022-04-26 02:54 UTC, TimelikeClosure approved these changes

2022-04-26 02:54 UTC, tiffanylin706 commented
<img width="1203" alt="截圖 2022-04-25 下午7 54 07" src="https://user-images.githubusercontent.com/103457249/165210709-b82533f0-21ee-4f0a-84ff-15951171c29a.png">

2022-04-26 02:58 UTC, merged