ds-prep-python-tuples exercise_Tiffany Lin
tiffanylin706/ds-py-0422-code-solutions pull request #5
Opened 2022-04-27 20:26 UTC by tiffanylin706

<img width="1223" alt="截圖 2022-04-27 下午1 22 37" src="https://user-images.githubusercontent.com/103457249/165625017-659640da-c829-4af3-9531-b8f7afbb90e2.png">

2022-04-27 23:02 UTC, tiffanylin706 commented
<img width="1247" alt="截圖 2022-04-27 下午4 02 08" src="https://user-images.githubusercontent.com/103457249/165645216-42b7f6ad-e53b-4f14-8498-27679382888b.png">

2022-04-28 00:13 UTC, TimelikeClosure requested changes

2022-04-28 00:13 UTC, TimelikeClosure commented on ds-prep-python-tuples/main.py
> +age= print("age:", (passenger[-1]))
Make sure you're assigning the value to the variable _first_, then `print`ing that variable _second_:

---

![image](https://user-images.githubusercontent.com/16143771/165650805-aac9722c-7d3c-4822-8cdc-47ea91cc6654.png)

2022-04-28 01:42 UTC, tiffanylin706 commented
<img width="1254" alt="截圖 2022-04-27 下午6 41 54" src="https://user-images.githubusercontent.com/103457249/165659370-8762c568-20d9-4181-a67a-daefc585f56f.png">

2022-04-28 01:47 UTC, TimelikeClosure approved these changes

2022-04-28 01:48 UTC, merged